version: '3' # Versão do Docker Compose

services: # Define os serviços que serão criados
  # Serviço do Banco de Dados
  db:
    image: mysql:8.0 # Imagem do Docker que será usada
    container_name: database # Nome do container
    restart: unless-stopped # Política de reinício do container
    env_file: ./.env # Arquivo que contém as variáveis de ambiente
    environment: # Variáveis de ambiente específicas do serviço
      - MYSQL_DATABASE=$DB_NAME # Nome do banco de dados
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD # Senha do usuário root
    volumes: # Volumes que serão montados no container
      - data:/var/lib/mysql # Persistência dos dados do MySQL
  # Serviço da API
  api:
    build: . # Diretório que contém o Dockerfile
    image: crud-api:latest # Imagem do Docker que será construída
    depends_on: # Dependências do serviço
      - db # Este serviço depende do serviço db
    container_name: api # Nome do container
    env_file: ./.env # Arquivo que contém as variáveis de ambiente
    ports: # Portas que serão expostas pelo serviço
      - $API_PORT:$API_PORT # Porta da API
    volumes: # Volumes que serão montados no container
      - ./:/app # Código-fonte da API
    environment: # Variáveis de ambiente específicas do serviço
      - DB_HOST=$DB_HOST # Host do banco de dados
      - DB_USER=$DB_USER # Usuário do banco de dados
      - DB_PASSWORD=$DB_PASSWORD # Senha do banco de dados
      - DB_NAME=$DB_NAME # Nome do banco de dados

volumes: # Define os volumes que serão usados pelos serviços
  data: # Volume para persistência dos dados do MySQL